name: Update Changelog

on:
  push:
    branches:
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Run Update Changelog Action
        uses: MusfiqDehan/Auto-Update-CHANGELOG@v1
        with:
          version: '1.0.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
