name: Update Changelog

on:
  push:
    branches:
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the current version
        id: current-version
        run: echo "version=$(python setup.py --version)" >> $GITHUB_ENV
        shell: bash

      - name: Run Update Changelog Action
        uses: MusfiqDehan/Auto-Update-CHANGELOG@v1.0.3
        with:
          version: ${{ env.version }}
          user_email: 'musfiqur.rahaman@northsouth.edu'
          user_name: 'Md. Musfiqur Rahaman'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
